#' @title preText
#' @description Calculates preText scores for each preprocessing specification.
#' This is the main wrapper function that runs the full preText procedure.
#'
#' @param preprocessed_documents A list object generated by the
#' \code{factorial_preprocessing()} function.
#' @param dataset_name A string indicating the name to be associated with the
#' results. Defaults to "Documents".
#' @param distance_method The method that should be used for calculating
#' document distances. Defaults to "cosine".
#' @param num_comparisons The number of ranks to use in calculating average
#' difference. Defaults to 50.
#' @param parallel Logical indicating whether processing should be
#' performed in parallel. Defaults to FALSE.
#' @param cores Defaults to 1.
#' @param verbose Logical indicating whether to print progress. Defaults to TRUE.
#' @return A result list object with elements:
#' \itemize{
#'   \item \code{choices}: data.frame of preprocessing choices
#'   \item \code{labels}: labels for each specification
#'   \item \code{preText_scores}: data.frame of preText scores
#'   \item \code{ranked_preText_scores}: sorted preText scores
#'   \item \code{distance_matrices}: list of document distance matrices
#'   \item \code{regression_results}: results of preprocessing choice regressions
#' }
#' @examples
#' \dontrun{
#' library(preText2)
#' data("UK_Manifestos")
#' preprocessed_documents <- factorial_preprocessing(
#'     UK_Manifestos,
#'     use_ngrams = TRUE,
#'     infrequent_term_threshold = 0.02,
#'     verbose = TRUE)
#' preText_results <- preText(
#'     preprocessed_documents,
#'     dataset_name = "UK Manifestos",
#'     distance_method = "cosine",
#'     num_comparisons = 50,
#'     verbose = TRUE)
#' }
#' @export
preText <- function(preprocessed_documents,
                    dataset_name = "Documents",
                    distance_method = "cosine",
                    num_comparisons = 50,
                    parallel = FALSE,
                    cores = 1,
                    verbose = TRUE) {

    ptm <- proc.time()

    # extract the dfm object list
    dfm_object_list <- preprocessed_documents$dfm_list

    cat("Generating document distances...\n")
    scaling_results <- scaling_comparison(dfm_object_list,
                                          dimensions = 2,
                                          distance_method = distance_method,
                                          verbose = verbose,
                                          cores = cores)

    cat("Calculating preText scores...\n")
    preText_results <- preText_test(
        scaling_results$distance_matrices,
        choices = preprocessed_documents$choices,
        labels = preprocessed_documents$labels,
        baseline_index = nrow(preprocessed_documents$choices),
        num_comparisons = num_comparisons,
        parallel = parallel,
        cores = cores,
        verbose = verbose)

    # Run regressions
    regression_results <- preprocessing_choice_regression(
        preText_results$preText_scores,
        preprocessed_documents$choices)

    t <- proc.time() - ptm
    cat("Complete in", t[3], "seconds.\n")

    return(list(choices = preprocessed_documents$choices,
                labels = preprocessed_documents$labels,
                preText_scores = preText_results$preText_scores,
                ranked_preText_scores = preText_results$ranked_preText_scores,
                distance_matrices = scaling_results$distance_matrices,
                regression_results = regression_results,
                dataset_name = dataset_name))
}
