#' @title preText Test
#' @description Calculates preText scores for each preprocessing specification
#' by comparing document distance matrices.
#'
#' @param distance_matrices A list of document distance matrices generated by the
#' \code{scaling_comparison()} function.
#' @param choices A dataframe indicating whether a preprocessing step was
#' applied or not. Generated by \code{factorial_preprocessing()}.
#' @param labels Optional labels for each preprocessing step.
#' @param baseline_index The index of the baseline distance matrix.
#' Defaults to 128.
#' @param text_size The cex for text in plots. Defaults to 1.
#' @param num_comparisons The number of ranks to use. Defaults to 50.
#' @param parallel Logical for parallel processing. Defaults to FALSE.
#' @param cores Number of cores. Defaults to 1.
#' @param verbose Logical for printing progress. Defaults to TRUE.
#' @return A result list with \code{preText_scores} and
#' \code{ranked_preText_scores}.
#' @examples
#' \dontrun{
#' # This function is typically called inside preText().
#' }
#' @export
preText_test <- function(distance_matrices,
                          choices,
                          labels = NULL,
                          baseline_index = 128,
                          text_size = 1,
                          num_comparisons = 50,
                          parallel = FALSE,
                          cores = 1,
                          verbose = TRUE) {

    num_dms <- length(distance_matrices)

    # Adjust baseline_index if needed
    if (baseline_index > num_dms) {
        baseline_index <- num_dms
    }

    # Get baseline distance matrix
    baseline <- distance_matrices[[baseline_index]]

    scores <- rep(0, num_dms)
    score_SEs <- rep(0, num_dms)

    for (i in 1:num_dms) {
        if (verbose) {
            cat("Currently working on DFM:", i, "of", num_dms, "\n")
        }

        if (i != baseline_index) {
            dist_matrix <- distance_matrices[[i]]

            # Get ordering by max difference from baseline
            ordering <- get_max_difference(dist_matrix, baseline)

            # Compute score using the top num_comparisons pairs
            actual_comparisons <- min(num_comparisons, length(ordering))
            cur_scores <- rep(0, actual_comparisons)

            for (k in 1:actual_comparisons) {
                idx <- ordering[k]
                row_idx <- ((idx - 1) %/% nrow(dist_matrix)) + 1
                col_idx <- ((idx - 1) %% nrow(dist_matrix)) + 1
                cur_scores[k] <- abs(dist_matrix[row_idx, col_idx] -
                                         baseline[row_idx, col_idx])
            }

            scores[i] <- mean(cur_scores)
            score_SEs[i] <- stats::sd(cur_scores) / sqrt(actual_comparisons)
        }
    }

    # Create scores dataframe
    if (is.null(labels)) {
        labels <- paste0("spec_", 1:num_dms)
    }

    preText_scores <- data.frame(
        labels = labels,
        preText_score = scores,
        preText_score_SE = score_SEs,
        stringsAsFactors = FALSE)

    # Rank scores
    ranked <- preText_scores[order(preText_scores$preText_score,
                                    decreasing = TRUE), ]

    return(list(preText_scores = preText_scores,
                ranked_preText_scores = ranked))
}


#' Get ordering of pairwise distances by maximum difference from baseline
#'
#' @param dist_matrix A distance matrix.
#' @param baseline A baseline distance matrix.
#' @return An integer vector of indices ordered by absolute difference.
#' @keywords internal
get_max_difference <- function(dist_matrix, baseline) {
    # Compute absolute differences
    diffs <- abs(as.vector(dist_matrix) - as.vector(baseline))
    # Return indices ordered by decreasing difference
    return(order(diffs, decreasing = TRUE))
}
