#' @title Scaling Comparison.
#' @description Compares document scaling across multiple dfm objects by
#' computing pairwise document distance matrices.
#'
#' @param dfm_object_list A list of quanteda dfm objects generated by the
#' \code{factorial_preprocessing()} function and returned in the
#' \code{$dfm_list} field.
#' @param dimensions The number of dimensions to use for scaling. Defaults to 2.
#' @param distance_method The method for calculating document distances.
#' Defaults to "cosine".
#' @param verbose Logical indicating whether to print progress. Defaults to TRUE.
#' @param cores Number of cores for parallel processing. Defaults to 1.
#' @return A list with elements:
#' \itemize{
#'   \item \code{distance_matrices}: list of distance matrices
#'   \item \code{dfm_list}: the input dfm list
#' }
#' @examples
#' \dontrun{
#' library(preText2)
#' data("UK_Manifestos")
#' preprocessed_documents <- factorial_preprocessing(
#'     UK_Manifestos,
#'     use_ngrams = FALSE,
#'     verbose = TRUE)
#' scaling_results <- scaling_comparison(
#'     preprocessed_documents$dfm_list,
#'     dimensions = 2,
#'     distance_method = "cosine",
#'     verbose = TRUE)
#' }
#' @export
scaling_comparison <- function(dfm_object_list,
                                dimensions = 2,
                                distance_method = "cosine",
                                verbose = TRUE,
                                cores = 1) {

    num_dfms <- length(dfm_object_list)
    distance_matrices <- vector(mode = "list", length = num_dfms)

    for (i in 1:num_dfms) {
        if (verbose) {
            cat("Calculating distances for DFM", i, "of", num_dfms, "\n")
        }

        cur_dfm <- dfm_object_list[[i]]

        if (distance_method == "cosine") {
            # Compute cosine distance manually: 1 - cosine_similarity
            # Normalize rows to unit length
            row_norms <- sqrt(Matrix::rowSums(cur_dfm^2))
            # Avoid division by zero
            row_norms[row_norms == 0] <- 1
            normed <- cur_dfm / row_norms
            sim_matrix <- as.matrix(normed %*% Matrix::t(normed))
            dist_matrix <- 1 - sim_matrix
        } else if (distance_method == "euclidean") {
            dist_matrix <- as.matrix(stats::dist(as.matrix(cur_dfm),
                                                  method = "euclidean"))
        } else {
            dist_matrix <- as.matrix(stats::dist(as.matrix(cur_dfm),
                                                  method = distance_method))
        }

        distance_matrices[[i]] <- dist_matrix
    }

    return(list(distance_matrices = distance_matrices,
                dfm_list = dfm_object_list))
}
